project_id = "lojfktirofxruyqdbgey"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-topic]
verify_jwt = false

[functions.personalized-chat]
verify_jwt = false